# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=21.2.0
FROM node:${NODE_VERSION}-slim as base

LABEL fly_launch_runtime="Next.js/Prisma"

# Next.js/Prisma app lives here
WORKDIR /app

# Set production environment
# ENV NODE_ENV="production"
ENV NODE_ENV="development"

ENV NEXT_PUBLIC_APP_DOMAIN="http://localhost:3000"

# Install pnpm
ARG PNPM_VERSION=8.10.5
RUN npm install -g pnpm@$PNPM_VERSION


FROM base

# Install packages needed for development
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y git && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives


# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install -y build-essential openssl pkg-config python-is-python3

# Install node modules
COPY --link package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Generate Prisma Client
COPY --link prisma .
RUN npx prisma generate

# Copy application code
COPY --link . .

# Run development server
EXPOSE 3000
CMD [ "pnpm", "run", "dev" ]